### PR TITLE
add missing tftp in an example.

### PR DESCRIPTION
**Pull request by m-tmatma**
add missing tftp in an example.

### CODE REVIEW

**Comment by pin** [comment]
Thanks!!

**Comment by m-tmatma** [comment]
@pin 
You closed without merging?

**Comment by m-tmatma** [comment]
@pin 
This PR was closed without merged.
Could you reopen and merge this?

**Comment by pin** [comment]
Sorry, my bad.

**Comment by m-tmatma** [comment]
@pin 
Thanks

**Pull request merged**
