### PR TITLE
Expose peer address to handler functions

### PR DESCRIPTION
**Pull request by acd**

### CODE REVIEW

**Comment by pin** [comment]
LGTM!

If you have time please mention that {Incoming,Outgoing}Transfer is exposes remote address (for logging purposes I assume). Also while you are there don't forget to add you in CONTRIBUTORS file :+1:

If not will merge it as is and do that myself before cutting next release soon.

**Comment by pin** [comment]
On "mention" I mean updating godoc comment for that two types. Thanks!

**Comment by acd** [comment]
Will do.  And yes, I made this change to facilitate client IP logging when implementing a server.

**Comment by pin** [comment]
Looks great! :+1:

**Pull request merged**
